server:
  port: 8040

spring:
  application:
    name: microservice-center-zuul-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

zuul:
  ignored-services: '*'
  routes:
    api-user-manage: # 配置 microservice-framework-user-manage 微服务路由信息
      path: /framwork-user-manage/**
      serviceId: microservice-framework-user-manage
  sensitiveHeaders: Cookie,Set-Cookie,Authorization
  add-host-header: true #设为true才能保持Host头信息处理正确
  retryable: true # 重试

ribbon:
  ConnectTimeout: 250
  ReadTimeout: 1000 #请求处理的超时时间
  OkToRetryOnAllOperations: true #对所有请求操作都进行重试
  MaxAutoRetries: 0 #对当前服务的重试次数（第一次分配给9082的时候，如果404，则再重试MaxAutoRetries次，如果还是404，则切换到其他服务MaxAutoRetriesNextServer决定）
  MaxAutoRetriesNextServer: 1  #切换服务的次数(比如本次请求分配给9082处理，发现404，则切换分配给9081处理，如果还是404，则返回404给客户端）

logging:
  config: classpath:logback.xml

info:
  description: 网关
