server:
  port: 8001
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tuacy/spring-cloud-config.git
          default-label: master
eureka:
    client:
      service-url:
        #注册中心地址，逗号隔开配置多个注册中心
        defaultZone:  http://localhost:8761/eureka
    instance:
      #向注册中心注册IP
      prefer-ip-address: true
      appname: config-server
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
info:
  description: 配置中心